[package]
name = "TestProjekt"
version = "0.1.0"
authors = ["Szymon <wieczorek0725@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
cgmath = "0.17.0"